export const STORAGE_KEY = 'SmartPigs';
export const UPDATE_URL = 'UPDATE_URL';
export const UPDATE_LANG = 'UPDATE_LANG';
export const TOGGLE_DIRTY = 'TOGGLE_DIRTY';
export const UPDATE_MENU_TYPE = 'UPDATE_MENU_TYPE';
export const UPDATE_DATE_FORMAT = 'UPDATE_DATE_FORMAT';
export const UPDATE_PROGRAM_LANG = 'UPDATE_PROGRAM_LANG';

export const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';
export const UPDATE_CREDENTIALS_FIELD = 'UPDATE_CREDENTIALS_FIELD';

export const NAVIGATE_TO = 'NAVIGATE_TO';
export const SERVER_REQUEST = 'SERVER_REQUEST';

export const CREATE_ERROR = 'CREATE_ERROR';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS';

export const THROW_ERROR = 'THROW_ERROR';
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
export const UPDATE_SPINNER = 'UPDATE_SPINNER';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';
export const RESET_SESSION_DATA = 'RESET_SESSION_DATA';
export const UPDATE_SESSION_DATA = 'UPDATE_SESSION_DATA';

export const UPDATE_FILE_ID = 'UPDATE_FILE_ID';
